import Link from "next/link";import {tools,type Tool,categoryPath,type Category} from "@/lib/tools";
const themes={calculators:{eyebrow:"＋ 01 · CALCULATE",how:"How the calculator works",related:"More calculators",icon:"∑",other:"Explore finance & utility tools"},finance:{eyebrow:"₹ 01 · FINANCE",how:"How the finance calculation works",related:"More finance tools",icon:"₹",other:"Explore calculators & utilities"},dev:{eyebrow:"{ } 01 · DEVELOP",how:"How this developer tool works",related:"More developer tools",icon:"</>",other:"Explore calculators, finance & SEO"},seo:{eyebrow:"⌕ 01 · OPTIMIZE",how:"How this SEO tool works",related:"More SEO tools",icon:"#",other:"Explore developer & calculator tools"},files:{eyebrow:"⇩ 01 · PROCESS",how:"How this file tool works",related:"More file tools",icon:"PDF",other:"Explore developer & SEO tools"}} as const;
const categoryNames:Record<Category,string>={calculators:"Calculators",finance:"Finance",dev:"Developer Tools",seo:"SEO Tools",files:"File Tools"};
const genericSteps=(tool:Tool)=>["Enter or upload the required input.","Run the tool and review the generated result.","Check assumptions, formatting and output before using it elsewhere."];
const cross={calculators:["finance","dev","seo","files"],finance:["calculators","dev","seo","files"],dev:["calculators","finance","seo","files"],seo:["calculators","finance","dev","files"],files:["calculators","finance","dev","seo"]} as Record<Category,Category[]>;
export default function ToolContent({slug,tool}:{slug:string;tool:Tool}){
 const th=themes[tool.category];const related=Object.entries(tools).filter(([s,t])=>s!==slug&&t.category===tool.category);
 const crossLinks=cross[tool.category].map(cat=>[cat,Object.entries(tools).filter(([,t])=>t.category===cat).slice(0,4)] as const);
 return <div className={`container pb-24 content-${tool.category}`}>
 <section className="content-section intro-section"><div className="section-mark">{th.icon}</div><span className="eyebrow">{th.eyebrow}</span><h2>What is {tool.title}?</h2><p>{tool.intro}</p></section>
 <section className="content-section"><span className="eyebrow">{th.icon} 02 · UNDERSTAND</span><h2>{th.how}</h2><div className="step-grid">{genericSteps(tool).map((x,i)=><article className="info-card" key={x}><span>0{i+1}</span><h3>{x}</h3><p>{i===0?"Use the fields in the interactive tool above. Keep numbers, dates, URLs or files in the expected format.":i===1?"The result updates in the browser and is presented in a clear output card.":"Important decisions should be checked against the latest official or authoritative information."}</p></article>)}</div></section>
 <section className="content-section formula-section"><span className="eyebrow">{th.icon} 03 · FORMULA / LOGIC</span><h2>Which formula or logic is used?</h2><div className="formula-panel"><span>{th.icon}</span><code>{tool.formula}</code></div><p className="muted">The formula above describes the core logic of this version. Real-world financial, tax, exchange-rate and file-processing rules can have additional conditions.</p></section>
 <section className="content-section"><span className="eyebrow">✦ 04 · IMPORTANT</span><h2>Things to know before using {tool.title}</h2><div className="tips-grid">{tool.tips.map((x,i)=><article className="tip-card" key={x}><b>0{i+1}</b><p>{x}</p></article>)}</div></section>
 <section className="content-section faq-section"><span className="eyebrow">? 05 · FAQ</span><h2>Frequently Asked Questions</h2><div className="faq-list">{tool.faq.map((q,i)=><details key={q} className="faq-item" open={i===0}><summary>{q}<span>+</span></summary><p>{i===0?tool.description:i===1?tool.formula:i===2?"Yes. The page is responsive and optimized for desktop, tablet and mobile.":"Browser-first interactions process data locally where possible. Sensitive files should be handled according to your privacy requirements."}</p></details>)}</div></section>
 <section className="content-section related-section"><span className="eyebrow">→ 06 · SAME CATEGORY</span><h2>{th.related}</h2><p>Continue through the complete {categoryNames[tool.category]} collection.</p><div className="related-grid">{related.map(([s,t],i)=><Link href={categoryPath(t,s)} key={s} className="related-card"><span>{["✦","＋","⌕","{ }","₹","PDF","#","→"][i%8]}</span><div><strong>{t.title}</strong><small>{t.description}</small></div><b>→</b></Link>)}</div></section>
 <section className="content-section cross-link-section"><span className="eyebrow">✦ 07 · DISCOVER MORE</span><h2>Related Tools Across CalcIndia</h2><p>Every section of CalcIndia is connected, so visitors can move naturally between calculators, finance, developer, SEO and file tools.</p>
 <div className="mt-8 space-y-8">{crossLinks.map(([cat,items])=><div key={cat}><h3 className="mb-4 text-xl font-black">{categoryNames[cat]}</h3><div className="related-grid">{items.map(([s,t])=><Link href={categoryPath(t,s)} key={s} className="related-card"><span>✦</span><div><strong>{t.title}</strong><small>{t.description}</small></div><b>→</b></Link>)}</div><Link href={"/"+cat} className="mt-4 inline-block text-sm font-bold text-cyan-300">View all {categoryNames[cat]} →</Link></div>)}</div>
 </section>
 <section className="content-section"><span className="eyebrow">◎ 08 · CATEGORY HUBS</span><h2>Explore CalcIndia</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(["calculators","finance","dev","seo","files"] as Category[]).filter(c=>c!==tool.category).map(c=><Link href={"/"+c} key={c} className="glass hover-lift rounded-2xl p-5"><b>{categoryNames[c]}</b><p className="mt-2 text-sm text-slate-500">Explore all {categoryNames[c].toLowerCase()}.</p><span className="mt-4 block text-sm text-cyan-300">Explore →</span></Link>)}</div></section>
 </div>
}