const icons: Record<string, string> = {
  salary: "🧮",
  emi: "🧮",
  sip: "🧮",
  gst: "🧮",
  tax: "🧮",
  age: "🧮",
  percentage: "🧮",
  eligibility: "🧮",
  fd: "🧮",
  rd: "🧮",
  ppf: "🧮",
  nps: "🧮",
  gratuity: "🧮",
  hra: "🧮",
  epf: "🧮",
  compound: "🧮",
  inflation: "🧮",
  bmi: "🧮",
  date: "🧮",
  time: "🧮",
  discount: "🧮",
  profit: "🧮",
  currency: "🧮",
  "json-format": "</>",
  "json-validate": "</>",
  base64: "</>",
  uuid: "</>",
  url: "</>",
  password: "</>",
  qr: "</>",
  html: "</>",
  css: "</>",
  js: "</>",
  regex: "</>",
  timestamp: "</>",
  color: "</>",
  meta: "⌕",
  robots: "⌕",
  sitemap: "⌕",
  "image-compress": "🖼",
  "image-resize": "🖼",
  "image-convert": "📄",
  "image-webp": "📄",
  "pdf-compress": "📄",
  "pdf-merge": "📄",
  "pdf-split": "📄",
  "pdf-jpg": "📄",
  "jpg-pdf": "📄",
  resume: "📄",
};

export default function ToolIcon({ kind }: { kind: string }) {
  return <span className="home-icon" aria-hidden="true">{icons[kind] ?? "✦"}</span>;
}
